2025-01-26 09:03:38,019 - app.components.routers.parse - ERROR - 删除记录失败 record_id: 6794773b8cd6534bed5c55c9, 错误: 404: Record not found
Traceback (most recent call last):
  File "D:\Code\Python\LLM-Kit\app\components\routers\parse.py", line 754, in delete_record
    raise HTTPException(status_code=404, detail="Record not found")
fastapi.exceptions.HTTPException: 404: Record not found
2025-01-26 09:03:55,069 - app.components.routers.parse - ERROR - 删除文件失败 file_id: 679479eb7e25968cd63194d9, 错误: 404: File not found
Traceback (most recent call last):
  File "D:\Code\Python\LLM-Kit\app\components\routers\parse.py", line 729, in delete_file
    raise HTTPException(status_code=404, detail="File not found")
fastapi.exceptions.HTTPException: 404: File not found
2025-01-26 09:05:20,257 - app.components.routers.to_tex - ERROR - 删除LaTeX记录失败 record_id: 6794e06350fef7924629f762, 错误: 404: Record not found
Traceback (most recent call last):
  File "D:\Code\Python\LLM-Kit\app\components\routers\to_tex.py", line 133, in delete_tex_record
    raise HTTPException(status_code=404, detail="Record not found")
fastapi.exceptions.HTTPException: 404: Record not found
